# SPDX-FileCopyrightText: Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

name: "Benchmarks"
permissions: read-all

on:
  workflow_dispatch:
  # 6am UTC is 10pm PST, 11pm PDT
  schedule:
    - cron: '0 6 * * *'

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  gbench:
    runs-on: pvc
    name: "JFCST Benchmarks"
    env:
      CXX: icpx
      FI_PROVIDER: tcp
    steps:
      - uses: actions/checkout@v4
      - name: Generate
        run: cmake -B build
      - name: Build/Run
        run: |
          # Install drbench into python virtual environment
          /home/rscohn1/miniforge3/bin/python -m venv venv
          source venv/bin/activate
          pip install src-python/drbench
          # Allocate 2 nodes. Builds on this node and drbench uses
          # mpiexec to launch the work on the compute nodes.
          salloc --nodes=2 make -C build/benchmarks/gbench jfcst-bench
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: benchmarks
          path: |
            build/benchmarks
